# Generated by Django 4.1.2 on 2022-11-23 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alternative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("text", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Preference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.poll"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MajorityOpinionPoll",
            fields=[
                (
                    "poll_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="polls.poll",
                    ),
                ),
            ],
            bases=("polls.poll",),
        ),
        migrations.CreateModel(
            name="SinglePreferencePoll",
            fields=[
                (
                    "poll_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="polls.poll",
                    ),
                ),
            ],
            bases=("polls.poll",),
        ),
        migrations.CreateModel(
            name="MajorityOpinionJudgement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade",
                    models.IntegerField(
                        choices=[
                            (1, "Pessimo"),
                            (2, "Mediocre"),
                            (3, "Buono"),
                            (4, "Discreto"),
                            (5, "Ottimo"),
                        ]
                    ),
                ),
                (
                    "alternative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.alternative",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="alternative",
            name="poll",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="polls.poll"
            ),
        ),
        migrations.CreateModel(
            name="SinglePreference",
            fields=[
                (
                    "preference_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="polls.preference",
                    ),
                ),
                (
                    "alternative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.alternative",
                    ),
                ),
            ],
            bases=("polls.preference",),
        ),
        migrations.CreateModel(
            name="MajorityPreference",
            fields=[
                (
                    "preference_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="polls.preference",
                    ),
                ),
                (
                    "responses",
                    models.ManyToManyField(
                        through="polls.MajorityOpinionJudgement", to="polls.alternative"
                    ),
                ),
            ],
            bases=("polls.preference",),
        ),
        migrations.AddField(
            model_name="majorityopinionjudgement",
            name="preference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.majoritypreference",
            ),
        ),
    ]
