# Generated by Django 4.1.2 on 2022-11-18 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Question",
            new_name="Poll",
        ),
    ]
