# Generated by Django 4.1.2 on 2022-11-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alternative",
            name="text",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="poll",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
