# Generated by Django 4.1.2 on 2022-11-18 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_rename_question_poll"),
    ]

    operations = [
        migrations.RenameField(
            model_name="choice",
            old_name="question",
            new_name="poll",
        ),
        migrations.RenameField(
            model_name="poll",
            old_name="question_text",
            new_name="text",
        ),
        migrations.RenameField(
            model_name="vote",
            old_name="question",
            new_name="poll",
        ),
    ]
