# Generated by Django 4.1.2 on 2022-12-23 14:09

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_alter_alternative_text_alter_poll_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="end",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 12, 23, 14, 9, 14, 442658, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="poll",
            name="start",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="majorityopinionjudgement",
            name="grade",
            field=models.IntegerField(
                choices=[
                    (1, "Pessimo"),
                    (2, "Scarso"),
                    (3, "Sufficiente"),
                    (4, "Buono"),
                    (5, "Ottimo"),
                ]
            ),
        ),
    ]
