# Generated by Django 4.1.2 on 2023-01-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_poll_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="majoritypreference",
            name="synthetic",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="singlepreference",
            name="synthetic",
            field=models.BooleanField(default=False),
        ),
    ]
