# Generated by Django 4.1.2 on 2022-11-23 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_rename_question_choice_poll_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Choice",
            new_name="Alternative",
        ),
        migrations.RenameModel(
            old_name="Vote",
            new_name="Preference",
        ),
    ]
