# Generated by Django 4.1.2 on 2023-01-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_poll_end_poll_start_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="default_type",
            field=models.IntegerField(
                choices=[
                    (1, "Giudizio maggioritario"),
                    (2, "Metodo Shultze"),
                    (3, "Preferenza singola"),
                ],
                default=1,
            ),
        ),
    ]
