# Generated by Django 4.1.2 on 2022-11-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_rename_choice_alternative_rename_vote_preference"),
    ]

    operations = [
        migrations.RenameField(
            model_name="alternative",
            old_name="choice_text",
            new_name="text",
        ),
        migrations.RenameField(
            model_name="preference",
            old_name="choice",
            new_name="alternative",
        ),
        migrations.AddField(
            model_name="poll",
            name="title",
            field=models.CharField(default="-", max_length=50),
            preserve_default=False,
        ),
    ]
