# Generated by Django 4.1.2 on 2023-01-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0005_alter_poll_default_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="default_type",
            field=models.IntegerField(
                choices=[(1, "Giudizio maggioritario"), (3, "Preferenza singola")],
                default=1,
            ),
        ),
    ]
