# Generated by Django 4.1.2 on 2023-02-17 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_majoritypreference_synthetic_and_more"),
        ("polls", "0006_alter_poll_default_type"),
    ]

    operations = []
