# Generated by Django 4.1.2 on 2023-03-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0007_merge_20230217_1805"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="text",
            field=models.TextField(default=""),
        ),
    ]
