# Generated by Django 4.1.2 on 2023-03-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0008_mapping"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mapping",
            name="link",
        ),
        migrations.AddField(
            model_name="mapping",
            name="code",
            field=models.TextField(blank=True, unique=True),
        ),
    ]
