# Generated by Django 4.1.2 on 2023-03-06 20:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0008_alter_poll_text"),
        ("polls", "0008_poll_visibility"),
    ]

    operations = []
