# Generated by Django 4.1.2 on 2023-03-06 16:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0008_poll_visibility"),
        ("polls", "0009_remove_mapping_link_mapping_code"),
    ]

    operations = []
