# Generated by Django 4.1.2 on 2023-03-09 15:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0009_merge_0008_alter_poll_text_0008_poll_visibility"),
        ("polls", "0011_add_mapping_older_polls"),
    ]

    operations = []
