# Generated by Django 4.1.2 on 2023-03-17 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0013_alter_mapping_code_alter_poll_visibility"),
    ]

    operations = [
        migrations.CreateModel(
            name="PollOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("random_order", models.BooleanField(default=True)),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.poll"
                    ),
                ),
            ],
        ),
    ]
