# Generated by Django 4.1.2 on 2023-03-28 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polls", "0015_alter_mapping_poll_alter_polloptions_poll"),
    ]

    operations = [
        migrations.AddField(
            model_name="polloptions",
            name="authentication_required",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="AuthenticatedPoll",
            fields=[
                (
                    "poll_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="polls.poll",
                    ),
                ),
                (
                    "users_have_voted",
                    models.ManyToManyField(to=settings.AUTH_USER_MODEL),
                ),
            ],
            bases=("polls.poll",),
        ),
    ]
