# Generated by Django 4.1.2 on 2023-03-31 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polls", "0015_alter_mapping_poll_alter_polloptions_poll"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenizedPoll",
            fields=[
                (
                    "poll_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="polls.poll",
                    ),
                ),
            ],
            bases=("polls.poll",),
        ),
        migrations.AddField(
            model_name="poll",
            name="vote_type",
            field=models.IntegerField(
                choices=[(1, "Libero"), (2, "Solo autenticati"), (3, "Solo con token")],
                default=1,
            ),
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255)),
                ("has_already_used", models.BooleanField(default=False)),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.tokenizedpoll",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuthenticatedPoll",
            fields=[
                (
                    "poll_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="polls.poll",
                    ),
                ),
                (
                    "users_have_voted",
                    models.ManyToManyField(to=settings.AUTH_USER_MODEL),
                ),
            ],
            bases=("polls.poll",),
        ),
    ]
