# Generated by Django 4.1.2 on 2023-04-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0016_tokenizedpoll_poll_vote_type_token_authenticatedpoll"),
    ]

    operations = [
        migrations.RenameField(
            model_name="authenticatedpoll",
            old_name="users_have_voted",
            new_name="users_that_have_voted",
        ),
        migrations.RenameField(
            model_name="token",
            old_name="has_already_used",
            new_name="used",
        ),
        migrations.AlterField(
            model_name="poll",
            name="vote_type",
            field=models.IntegerField(
                choices=[
                    (1, "Libero"),
                    (2, "Solo autenticati"),
                    (3, "Solo con password"),
                ],
                default=1,
            ),
        ),
    ]
