# Generated by Django 4.1.2 on 2023-04-01 21:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "polls",
            "0017_rename_users_have_voted_authenticatedpoll_users_that_have_voted_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="poll",
            old_name="vote_type",
            new_name="authentication_type",
        ),
    ]
