# Generated by Django 4.1.2 on 2023-05-09 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0019_poll_results_restriction"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShultzeOpinionJudgement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "alternative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.alternative",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="poll",
            name="default_type",
            field=models.IntegerField(
                choices=[
                    (1, "Giudizio maggioritario"),
                    (2, "Metodo Shultze"),
                    (3, "Preferenza singola"),
                ],
                default=1,
            ),
        ),
        migrations.CreateModel(
            name="ShultzePreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("synthetic", models.BooleanField(default=False)),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.poll"
                    ),
                ),
                (
                    "responses",
                    models.ManyToManyField(
                        through="polls.ShultzeOpinionJudgement", to="polls.alternative"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="shultzeopinionjudgement",
            name="preference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.shultzepreference",
            ),
        ),
    ]
