# Generated by Django 4.1.2 on 2023-05-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0020_shultzeopinionjudgement_alter_poll_default_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="default_type",
            field=models.IntegerField(
                choices=[
                    (1, "Giudizio maggioritario"),
                    (2, "Metodo Schulze"),
                    (3, "Preferenza singola"),
                ],
                default=1,
            ),
        ),
    ]
